plugins {
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'beat.osu'
version = '1.0-SNAPSHOT'

application {
    mainModule = 'beat.osu.server'
    mainClass = 'beat.osu.server.Main'
}

dependencies {
    implementation project(':shared')

    implementation 'mysql:mysql-connector-java:8.0.32'
}

shadowJar {
    archiveBaseName = 'beatosu-server'
    archiveClassifier = ''
    manifest {
        attributes 'Main-Class': 'beat.osu.server.Main'
    }
    mergeServiceFiles()
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
