package beat.osu.client.enums;

public enum GameEventType {
    SCORE_CHANGED,
    COMBO_CHANGED,
    HIT_OBJECT_HIT,
    HIT_OBJECT_MISSED,
    GAME_STARTED,
    GAME_PAUSED,
    GAME_RESUMED,
    GAME_ENDED, HEALTH_CHANGED,
    ACCURACY_CHANGED,
    ADDITIONAL_SPIN,
    INPUT_OVERLAY_CHANGED,
}
